"""
D-04 — Air mass flow by speed density.

DEFECT
------
File  : src/l2_digital_twin/thermo_mechanical_twin.py
Lines : 151-152, then 162-165

    m_dot_air = fuel.value * afr_tv.value                      # line 151
    ...
    theoretical_m_dot_air = rho_tv.value * displacement_m3 * (rpm / 120.0)
    eta_v = m_dot_air_tv.value / theoretical_m_dot_air          # line 165

Air is derived FROM fuel, and volumetric efficiency is then back-solved from
that air. The causation runs backwards.

WHAT IS WRONG WITH IT
---------------------
1. THE MAP SENSOR DOES NO WORK. `map_counts` was added to the raw record and
   `map_pressure` to the normalised record specifically to drive the air
   estimate. In the shipped path it never enters the mass-flow calculation.

2. COMBINED WITH D-03, AIR BECOMES A CONSTANT MULTIPLE OF FUEL. Line 151 uses
   `afr_tv`, which comes from `lambda_sensor` — pinned at 1.0 by D-03. So
   AFR is always 14.7 and air is always 14.7 x fuel. Volumetric efficiency,
   back-solved from that, is then not an independent quantity either.

3. NOTHING CAN DISAGREE. When air is defined as fuel x AFR, the air/fuel
   ratio cannot be measured — it is assumed. Any fault that changes trapped
   air (ring blow-by, a restricted intake, a wastegate fault) is invisible,
   because the model has no way to notice that less air arrived than the
   fuelling assumed.

THE CORRECT DIRECTION
---------------------
    MAP + RPM + eta_vol  ->  air mass flow        (this file)
    air + fuel           ->  lambda               (D-03)
    lambda               ->  combustion efficiency (D-03)

    m_dot_air = eta_vol * rho_manifold * V_d * N / 120

The /120 divisor is the four-stroke cycle rate: one intake event per cylinder
per two crankshaft revolutions.

Requirements: SRD-FUN-027
"""

from __future__ import annotations

import math

R_AIR_J_PER_KG_K = 287.0528


def manifold_charge_density(map_pa: float, charge_temp_k: float) -> float:
    """Ideal-gas density of the intake charge, kg/m^3."""
    if map_pa <= 0.0 or charge_temp_k <= 0.0:
        return 0.0
    return map_pa / (R_AIR_J_PER_KG_K * charge_temp_k)


def volumetric_efficiency(rpm: float, map_pa: float, ambient_pa: float,
                          rated_rpm: float = 5800.0) -> float:
    """Volumetric efficiency estimate for a turbocharged four-stroke.

    PROVENANCE WARNING — SRD-CON-003.
    A runtime map must be GENERATED by the first-principles model offline and
    carry recorded provenance; it must not be a hand-fitted curve. The shape
    below is a PLACEHOLDER with the correct qualitative behaviour (peak in the
    mid range, mildly boost-dependent) and is labelled as such so it cannot be
    mistaken for a derived map.

    Replace this function with a lookup into the map generated by the L1
    crank-angle model across the operating envelope, validated against the
    manufacturer performance deck. Until that exists, treat any
    eta_vol-dependent result as provisional and say so in the output.
    """
    if rpm <= 0.0:
        return 0.0
    rpm_n = min(max(rpm / rated_rpm, 0.0), 1.2)
    base = 0.80 + 0.16 * math.sin(math.pi * min(rpm_n, 1.0))
    if ambient_pa > 0.0:
        pressure_ratio = min(max(map_pa / ambient_pa, 0.3), 2.5)
        base *= 0.96 + 0.04 * pressure_ratio
    return min(max(base, 0.0), 1.2)


def air_mass_flow_speed_density(
    rpm: float,
    map_pa: float,
    charge_temp_k: float,
    displacement_m3: float,
    eta_vol: float,
) -> float:
    """Air mass flow by speed density, kg/s.

    DROP-IN REPLACEMENT for thermo_mechanical_twin.py line 151.
    """
    if rpm <= 0.0 or map_pa <= 0.0 or charge_temp_k <= 0.0 \
            or displacement_m3 <= 0.0 or eta_vol <= 0.0:
        return 0.0
    rho = manifold_charge_density(map_pa, charge_temp_k)
    return eta_vol * rho * displacement_m3 * rpm / 120.0


def solve_air_flow(
    rpm: float,
    map_pa: float,
    ambient_pa: float,
    ambient_temp_k: float,
    displacement_m3: float,
    charge_temp_rise_k: float = 28.0,
) -> tuple[float, float, float, bool, str]:
    """Convenience wrapper returning the full air-path state.

    Returns (m_dot_air_kg_s, eta_vol, rho_manifold, valid, reason).
    """
    if rpm <= 0.0 or map_pa <= 0.0 or displacement_m3 <= 0.0:
        return 0.0, 0.0, 0.0, False, "Non-positive rpm, MAP or displacement"
    charge_temp_k = ambient_temp_k + charge_temp_rise_k
    if charge_temp_k <= 0.0:
        return 0.0, 0.0, 0.0, False, "Non-physical charge temperature"

    eta_v = volumetric_efficiency(rpm, map_pa, ambient_pa)
    rho = manifold_charge_density(map_pa, charge_temp_k)
    m_dot = air_mass_flow_speed_density(rpm, map_pa, charge_temp_k,
                                        displacement_m3, eta_v)
    return m_dot, eta_v, rho, True, ""


if __name__ == "__main__":
    DISP = 1.352e-3          # Rotax 915 iS, m^3
    print("D-04  Air mass flow by speed density")
    print("\n  MAP now drives the air estimate (shipped code: it did not)")
    print(f"{'MAP kPa':>9}{'rpm':>7}{'eta_vol':>9}{'rho':>8}{'air kg/s':>10}")
    for map_kpa in (60, 80, 100, 120, 140):
        m, ev, rho, ok, _ = solve_air_flow(
            rpm=4000.0, map_pa=map_kpa * 1000.0, ambient_pa=101325.0,
            ambient_temp_k=288.15, displacement_m3=DISP)
        print(f"{map_kpa:9d}{4000:7d}{ev:9.3f}{rho:8.3f}{m:10.5f}")

    lo = solve_air_flow(4000.0, 70000.0, 101325.0, 288.15, DISP)[0]
    hi = solve_air_flow(4000.0, 140000.0, 101325.0, 288.15, DISP)[0]
    print(f"\n  doubling MAP 70->140 kPa raises air {hi / lo:.2f}x  "
          f"{'PASS' if hi > lo * 1.5 else 'FAIL'}")

    print("\n  shipped behaviour for comparison (air = fuel x AFR, AFR pinned):")
    for fuel in (0.002, 0.004, 0.006):
        print(f"    fuel {fuel:.4f} kg/s -> air {fuel * 14.7:.5f} kg/s "
              f"(independent of MAP, rpm and eta_vol)")
